### ISSUE TITLE
锐捷代理检测怎么破？

### ISSUE THREAD

**Issue by lipaopao000** [STARRY-S/Ruijie#1]
多设备共享一个热点时，会被检测出代理并禁网

**Comment by STARRY-S** [comment]
这个我也不知道锐捷是怎么检测用户的代理的，用了个月的路由器后因为学校的网速不好就再不用了，不过用路由器的那段时间没有检测到代理被禁网。
让设备流量全走ss貌似可行但国内的云服务器太贵了，水管又细，不建议尝试。

**Comment by STARRY-S** [comment]
值得一提的是我们学校的无线校园网在电脑登录的情况下共享wifi热点给其他设备，也没有被检测到代理。
